name: Generate Tokens On Input

on:
  push:
    paths:
      - 'input/design-tokens.json'

jobs:
  generate_tokens:
    runs-on: macos-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        id: 'auto-commit-action'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update platform deliverables
